services:

  php-fpm:
    container_name: php-fpm
    build: ./docker/php-fpm
    ports:
      - '8080:80'
    volumes:
      - ./laravel-project:/var/www/laravel-project
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
      - vendor-volume:/var/www/laravel-project/vendor # 動作が遅いことへの対策
      - storage-volume:/var/www/laravel-project/storage  # 動作が遅いことへの対策
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGPASSWORD: postgres
      POSTGRES_DB: main
      TZ: "Asia/Tokyo"
    ports:
      - 5432:5432 #MySQLと違うので注意
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
      - ./docker/postgres/logs:/var/log

# 動作が遅いことへの対策
volumes: 
  storage-volume:
  vendor-volume: