services:

  php-fpm:
    container_name: php-fpm
    build: ./docker/php-fpm
    ports:
      - '8080:80'
    volumes:
      - ./laravel-project:/var/www/laravel-project
      - vendor-volume:/var/www/laravel-project/vendor # 動作が遅いことへの対策
      - storage-volume:/var/www/laravel-project/storage  # 動作が遅いことへの対策

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: db-user
      MYSQL_PASSWORD: db-pass
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
    ports:
      - 3306:3306

# 動作が遅いことへの対策
volumes: 
  storage-volume:
  vendor-volume: