services:

  app:
    container_name: app
    build: ./docker/php
    ports:
      - '8000:80'
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./back:/var/www/back # 動作が遅いことへの対策 初回のdockerのbuild後、こちらのコメントアウトを外す
      - vendor-volume:/var/www/back/vendor # 動作が遅いことへの対策 laravelのプロジェクト作成後、コメントアウトを外す
      - storage-volume:/var/www/back/storage  # 動作が遅いことへの対策 laravelのプロジェクト作成後、コメントアウトを外す
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGPASSWORD: postgres
      POSTGRES_DB: main
      TZ: "Asia/Tokyo"
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
      - ./docker/postgres/logs:/var/log

# 動作が遅いことへの対策
volumes: 
  storage-volume:
  vendor-volume: